# Generated by Django 5.2 on 2025-04-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='membertype',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='officertype',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='salutation',
            old_name='created_by_username',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='school_year',
            old_name='created_by_username',
            new_name='created_by',
        ),
    ]
