# Generated by Django 5.2 on 2025-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salutation',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
