# Generated by Django 5.2 on 2025-04-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_salutation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='designation',
            new_name='position',
        ),
    ]
